server:
  port: 8080
  servlet:
    context-path: /EatzAPI

spring:
  application:
    name: eatz services
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: eatz_app
    url: jdbc:mysql://localhost:3306/eatz_app?useSSL=false&serverTimeZone=UTC
    password: eatz_app
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
    data:
      jpa.repositories.enabled: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect